### ISSUE TITLE
[Feature] Folders on top of the list

### ISSUE THREAD

**Issue by teddy-rogers** [jo-te/nova-explorer#1]
**Do you request a file icon or a folder icon?**
"Folder"

**Which endings or names shall it applied to?**
List endings or names here.
- All folders

**Which reference can be used?**
List here images or links to references e.g. the language logo.

**Comment by jo-te** [comment]
Am I understanding you correctly that you would like to have a feature, to toggle the order of the file browser items according to their type (`file` or `folder`) such that folders are always listed before files?

**Comment by jo-te** [comment]
Without feedback I will close this issue soon. :)

**Comment by thfrlw** [comment]
would love to see any configuration for this plugin, started using it accidentally because of new icons in nova 9 that I cant get used to.

**Comment by teddy-rogers** [comment]
> Am I understanding you correctly that you would like to have a feature, to toggle the order of the file browser items according to their type (`file` or `folder`) such that folders are always listed before files?

yeah exactly, sorry for responding so late

**Comment by jo-te** [comment]
@TeddRod `v1.1.0` now allows to change order of file browser items. :)
Also @thfrlw I added basic configuration option to hide specific items in file browser (currently only by exact matching). Maybe this improves your usage of this extension.
