### ISSUE TITLE
[Feature] Add Icons for Docker, Python and Env

### ISSUE THREAD

**Issue by DonsWayo** [jo-te/nova-explorer#2]
Hi!

First, very nice extension!

If is posible, I see some missing icons that can be included and also some ideas if the logo (with the format of the other icons)

- Dockerfile
-
![dockerfile-icon](https://user-images.githubusercontent.com/34981526/201681526-4d751535-c02d-4789-819f-84f36be2858c.jpeg)

- Env
![download](https://user-images.githubusercontent.com/34981526/201681556-131fa321-1833-43fa-b158-ca9192fc733b.png)

- Python
![text-x-python-icon](https://user-images.githubusercontent.com/34981526/201682214-77b4ca7d-cf1b-4857-8276-eedc08cd0ad8.png)

Also if you have any template to create the root of the icons and folder (sketch,psd,ai...) y also can help in create the png icons and many more that are missing.

Best regards

**Comment by jo-te** [comment]
Alright, thanks for your request, I added a file icon for Docker files and one for Python files:
![Docker file icon](https://github.com/jo-te/nova-explorer/blob/main/Explorer.novaextension/Images/docker-file/docker-file@2x.png?raw=true)
![Python file icon](https://github.com/jo-te/nova-explorer/blob/main/Explorer.novaextension/Images/python-file/python-file@2x.png?raw=true)

Please check under https://github.com/jo-te/nova-explorer/blob/main/src/config/fileEndingsImagePairs.ts if I added the correct file endings to be mapped.

For .env file I'm not quite sure regarding its design yet, therefore I will omit it for now.

**Comment by DonsWayo** [comment]
I think the file endings are okay.

Python has more endings but normally has different icons to avoid confusion.
